name: Release Desktop (Electron)

on:
  push:
    tags:
      - 'v*'
      - 'desktop-v*'

permissions:
  contents: write  # needed for creating GitHub Releases

jobs:
  build-and-publish:
    name: Build and Publish (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install
        working-directory: desktop

      - name: Build & Publish with electron-builder
        run: npm run dist -- -p always
        working-directory: desktop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

